name: Lint and Format

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Lint with luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: make lint

  format:
    name: Check formatting with stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stylua
        run: |
          wget -q https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/

      - name: Check formatting
        run: |
          stylua --check init.lua
          if [ $? -ne 0 ]; then
            echo "Formatting check failed. Run 'make format' locally to fix."
            exit 1
          fi
          echo "Formatting check passed"
